<a href="https://colab.research.google.com/github/MatthewFried/MAT5001/blob/main/M_Fried_M6_assn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1

In [ ]:
import numpy as np

#Write a code block that finds the distinct/unique common items between these two arrays:

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

output = np.intersect1d(a, b)
print(output)

[2 4]


Task 2

In [ ]:
#Create a 5x3 array (1,15) so that you do not need to explicitly key in every integer value.
vals = np.arange(1,16).reshape(3,5).T
print(vals)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Task 3

In [ ]:
#Flatten the above array 
flat = vals.T.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Task 4

In [ ]:
'''
Problem: Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column
becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and
the third column becomes the third dimension of the 3-D array.

Solution: I am trying to use numpy functions to do this, as requested.  Here's one approach, not sure if you meant this, so did it simpler below.  
The general approach is to use array so that we can convert the data using reshape
'''

data = vals.T
data = np.array(data)
data = data.reshape((data.shape[0], data.shape[1], 1))

print(data.shape)
print(data)

(3, 5, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [ ]:
#not sure if you meant this though

x = np.reshape(vals.T, (-1,3,5))
print(x.shape)
print(x)

(1, 3, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


Task 5

In [ ]:
#Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.
#solution from https://stackoverflow.com/a/51159213
#I'm pretty sure this is what you mean. 
#All we are doing is collapsing the dimensions with a reshape

new_img = x.reshape((x.shape[0]*x.shape[1]), x.shape[2])
print(new_img.T)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


Task 6

In [ ]:
#Write a Python/Numpy code block that removes from array a any items that are also present in array b.

a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

#not really using numpy, but simplest I think
#https://stackoverflow.com/a/52417992
c = set(a.flat) - set(b.flat)
print(c)

{8, 1, 15, 7}


In [ ]:
#another approach from same stackoverflow using numpy

#step 1: sort b and return the positions where each value was
#I've never seen any useful reason for argsort, so this is pretty neat
sidx = b.argsort()

#step 2: find the positions were if a were inserted into b they would belong via sidx found in the last step
idx = np.searchsorted(b,a,sorter=sidx)

#step 3: removes from a any items also present in b
out = a[b[sidx[idx]] != a]
print(out)

[ 7 15  1  8]


Task 7

In [ ]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

nyc_water = pandas.read_csv('https://raw.githubusercontent.com/MatthewFried/MAT5001/main/Module6_Data.csv').to_numpy()

type(nyc_water)

numpy.ndarray

In [ ]:
#get max NYC consumption of water 
#to solve, we find the max, using the max function on the columns

max = nyc_water.max(axis=0, keepdims=True)
print(max[:,2])

[1512.]


In [ ]:
#how many calender years are represented in this data
#to solve, we follow directions and use the shape function
nyc_water.shape

#from here we see there are 39 calendar years 

(39, 4)

In [ ]:
#What is the mean and the standard deviation of the per capita daily water consumption?
#To solve, we use the mean and std functions

the_mean = nyc_water.mean(axis=0, keepdims=True)
the_std = nyc_water.std(axis=0, keepdims=True)

print('Mean: ',the_mean[:,3], '\nStdev: ', the_std[:,3])

Mean:  [160.30769231] 
Stdev:  [31.5189433]


In [ ]:
#What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
#of differences and save that to a variable called "pop_diff", then print that variable to the screen
#To solve, we follow the directions and use diff, indicating we are looking for the columns

pop_diff = np.diff(nyc_water, axis = 0)

print(pop_diff[:,1])

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
